version: "3.7"

services:
  pvpgn:
    restart: unless-stopped
    container_name: pvpgn_server
    image: wwmoraes/pvpgn-server
    user: root
    volumes:
      - ./pvpgn/etc:/usr/local/pvpgn/etc
      - ./pvpgn/var:/usr/local/pvpgn/var
    ports:
      - 4000:4000
      - 6112:6112
      - 6200:6200

  ghostpp:
    restart: unless-stopped
    container_name: ghostpp_server
    image: fatorin/ghostpp:1.3
    user: root
    ports:
      - 6113:6113
      - 6114:6114
      - 6115:6115
    volumes:
      - ./ghostpp/config:/app/config
      - ./ghostpp/maps:/app/maps
    command: ./ghost++ "./config/ghost.cfg"

